// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.actor.getProfile

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// ActorGetProfile calls the XRPC method "app.gndr.actor.getProfile".
//
// actor: Handle or DID of account to fetch profile of.
func ActorGetProfile(ctx context.Context, c util.LexClient, actor string) (*ActorDefs_ProfileViewDetailed, error) {
	var out ActorDefs_ProfileViewDetailed

	params := map[string]interface{}{}
	params["actor"] = actor
	if err := c.LexDo(ctx, util.Query, "", "app.gndr.actor.getProfile", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
