// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.actor.getProfiles

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// ActorGetProfiles_Output is the output of a app.gndr.actor.getProfiles call.
type ActorGetProfiles_Output struct {
	Profiles []*ActorDefs_ProfileViewDetailed `json:"profiles" cborgen:"profiles"`
}

// ActorGetProfiles calls the XRPC method "app.gndr.actor.getProfiles".
func ActorGetProfiles(ctx context.Context, c util.LexClient, actors []string) (*ActorGetProfiles_Output, error) {
	var out ActorGetProfiles_Output

	params := map[string]interface{}{}
	params["actors"] = actors
	if err := c.LexDo(ctx, util.Query, "", "app.gndr.actor.getProfiles", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
