// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.embed.defs

// EmbedDefs_AspectRatio is a "aspectRatio" in the app.gndr.embed.defs schema.
//
// width:height represents an aspect ratio. It may be approximate, and may not correspond to absolute dimensions in any given unit.
type EmbedDefs_AspectRatio struct {
	Height int64 `json:"height" cborgen:"height"`
	Width  int64 `json:"width" cborgen:"width"`
}
