// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.feed.repost

import (
	comatprototypes "github.com/gander-social/gander-indigo-sovereign/api/atproto"
	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

func init() {
	util.RegisterType("app.gndr.feed.repost", &FeedRepost{})
} //
// RECORDTYPE: FeedRepost
type FeedRepost struct {
	LexiconTypeID string                         `json:"$type,const=app.gndr.feed.repost" cborgen:"$type,const=app.gndr.feed.repost"`
	CreatedAt     string                         `json:"createdAt" cborgen:"createdAt"`
	Subject       *comatprototypes.RepoStrongRef `json:"subject" cborgen:"subject"`
	Via           *comatprototypes.RepoStrongRef `json:"via,omitempty" cborgen:"via,omitempty"`
}
