// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.feed.like

import (
	comatprototypes "github.com/gander-social/gander-indigo-sovereign/api/atproto"
	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

func init() {
	util.RegisterType("app.gndr.feed.like", &FeedLike{})
} //
// RECORDTYPE: FeedLike
type FeedLike struct {
	LexiconTypeID string                         `json:"$type,const=app.gndr.feed.like" cborgen:"$type,const=app.gndr.feed.like"`
	CreatedAt     string                         `json:"createdAt" cborgen:"createdAt"`
	Subject       *comatprototypes.RepoStrongRef `json:"subject" cborgen:"subject"`
	Via           *comatprototypes.RepoStrongRef `json:"via,omitempty" cborgen:"via,omitempty"`
}
