// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.feed.getListFeed

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// FeedGetListFeed_Output is the output of a app.gndr.feed.getListFeed call.
type FeedGetListFeed_Output struct {
	Cursor *string                  `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Feed   []*FeedDefs_FeedViewPost `json:"feed" cborgen:"feed"`
}

// FeedGetListFeed calls the XRPC method "app.gndr.feed.getListFeed".
//
// list: Reference (AT-URI) to the list record.
func FeedGetListFeed(ctx context.Context, c util.LexClient, cursor string, limit int64, list string) (*FeedGetListFeed_Output, error) {
	var out FeedGetListFeed_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	params["list"] = list
	if err := c.LexDo(ctx, util.Query, "", "app.gndr.feed.getListFeed", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
