// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.feed.getFeedGenerators

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// FeedGetFeedGenerators_Output is the output of a app.gndr.feed.getFeedGenerators call.
type FeedGetFeedGenerators_Output struct {
	Feeds []*FeedDefs_GeneratorView `json:"feeds" cborgen:"feeds"`
}

// FeedGetFeedGenerators calls the XRPC method "app.gndr.feed.getFeedGenerators".
func FeedGetFeedGenerators(ctx context.Context, c util.LexClient, feeds []string) (*FeedGetFeedGenerators_Output, error) {
	var out FeedGetFeedGenerators_Output

	params := map[string]interface{}{}
	params["feeds"] = feeds
	if err := c.LexDo(ctx, util.Query, "", "app.gndr.feed.getFeedGenerators", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
