// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.feed.sendInteractions

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// FeedSendInteractions_Input is the input argument to a app.gndr.feed.sendInteractions call.
type FeedSendInteractions_Input struct {
	Interactions []*FeedDefs_Interaction `json:"interactions" cborgen:"interactions"`
}

// FeedSendInteractions_Output is the output of a app.gndr.feed.sendInteractions call.
type FeedSendInteractions_Output struct {
}

// FeedSendInteractions calls the XRPC method "app.gndr.feed.sendInteractions".
func FeedSendInteractions(ctx context.Context, c util.LexClient, input *FeedSendInteractions_Input) (*FeedSendInteractions_Output, error) {
	var out FeedSendInteractions_Output
	if err := c.LexDo(ctx, util.Procedure, "application/json", "app.gndr.feed.sendInteractions", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
