// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.graph.block

import (
	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

func init() {
	util.RegisterType("app.gndr.graph.block", &GraphBlock{})
} //
// RECORDTYPE: GraphBlock
type GraphBlock struct {
	LexiconTypeID string `json:"$type,const=app.gndr.graph.block" cborgen:"$type,const=app.gndr.graph.block"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	// subject: DID of the account to be blocked.
	Subject string `json:"subject" cborgen:"subject"`
}
