// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.graph.unmuteActorList

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// GraphUnmuteActorList_Input is the input argument to a app.gndr.graph.unmuteActorList call.
type GraphUnmuteActorList_Input struct {
	List string `json:"list" cborgen:"list"`
}

// GraphUnmuteActorList calls the XRPC method "app.gndr.graph.unmuteActorList".
func GraphUnmuteActorList(ctx context.Context, c util.LexClient, input *GraphUnmuteActorList_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "app.gndr.graph.unmuteActorList", nil, input, nil); err != nil {
		return err
	}

	return nil
}
