// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.graph.unmuteThread

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// GraphUnmuteThread_Input is the input argument to a app.gndr.graph.unmuteThread call.
type GraphUnmuteThread_Input struct {
	Root string `json:"root" cborgen:"root"`
}

// GraphUnmuteThread calls the XRPC method "app.gndr.graph.unmuteThread".
func GraphUnmuteThread(ctx context.Context, c util.LexClient, input *GraphUnmuteThread_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "app.gndr.graph.unmuteThread", nil, input, nil); err != nil {
		return err
	}

	return nil
}
