// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.graph.listblock

import (
	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

func init() {
	util.RegisterType("app.gndr.graph.listblock", &GraphListblock{})
} //
// RECORDTYPE: GraphListblock
type GraphListblock struct {
	LexiconTypeID string `json:"$type,const=app.gndr.graph.listblock" cborgen:"$type,const=app.gndr.graph.listblock"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	// subject: Reference (AT-URI) to the mod list record.
	Subject string `json:"subject" cborgen:"subject"`
}
