// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.graph.muteThread

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// GraphMuteThread_Input is the input argument to a app.gndr.graph.muteThread call.
type GraphMuteThread_Input struct {
	Root string `json:"root" cborgen:"root"`
}

// GraphMuteThread calls the XRPC method "app.gndr.graph.muteThread".
func GraphMuteThread(ctx context.Context, c util.LexClient, input *GraphMuteThread_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "app.gndr.graph.muteThread", nil, input, nil); err != nil {
		return err
	}

	return nil
}
