// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.graph.unmuteActor

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// GraphUnmuteActor_Input is the input argument to a app.gndr.graph.unmuteActor call.
type GraphUnmuteActor_Input struct {
	Actor string `json:"actor" cborgen:"actor"`
}

// GraphUnmuteActor calls the XRPC method "app.gndr.graph.unmuteActor".
func GraphUnmuteActor(ctx context.Context, c util.LexClient, input *GraphUnmuteActor_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "app.gndr.graph.unmuteActor", nil, input, nil); err != nil {
		return err
	}

	return nil
}
