// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.graph.muteActor

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// GraphMuteActor_Input is the input argument to a app.gndr.graph.muteActor call.
type GraphMuteActor_Input struct {
	Actor string `json:"actor" cborgen:"actor"`
}

// GraphMuteActor calls the XRPC method "app.gndr.graph.muteActor".
func GraphMuteActor(ctx context.Context, c util.LexClient, input *GraphMuteActor_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "app.gndr.graph.muteActor", nil, input, nil); err != nil {
		return err
	}

	return nil
}
