// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.graph.starterpack

import (
	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

func init() {
	util.RegisterType("app.gndr.graph.starterpack", &GraphStarterpack{})
} //
// RECORDTYPE: GraphStarterpack
type GraphStarterpack struct {
	LexiconTypeID     string                       `json:"$type,const=app.gndr.graph.starterpack" cborgen:"$type,const=app.gndr.graph.starterpack"`
	CreatedAt         string                       `json:"createdAt" cborgen:"createdAt"`
	Description       *string                      `json:"description,omitempty" cborgen:"description,omitempty"`
	DescriptionFacets []*RichtextFacet             `json:"descriptionFacets,omitempty" cborgen:"descriptionFacets,omitempty"`
	Feeds             []*GraphStarterpack_FeedItem `json:"feeds,omitempty" cborgen:"feeds,omitempty"`
	// list: Reference (AT-URI) to the list record.
	List string `json:"list" cborgen:"list"`
	// name: Display name for starter pack; can not be empty.
	Name string `json:"name" cborgen:"name"`
}

// GraphStarterpack_FeedItem is a "feedItem" in the app.gndr.graph.starterpack schema.
type GraphStarterpack_FeedItem struct {
	Uri string `json:"uri" cborgen:"uri"`
}
