// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.graph.getMutes

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// GraphGetMutes_Output is the output of a app.gndr.graph.getMutes call.
type GraphGetMutes_Output struct {
	Cursor *string                  `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Mutes  []*ActorDefs_ProfileView `json:"mutes" cborgen:"mutes"`
}

// GraphGetMutes calls the XRPC method "app.gndr.graph.getMutes".
func GraphGetMutes(ctx context.Context, c util.LexClient, cursor string, limit int64) (*GraphGetMutes_Output, error) {
	var out GraphGetMutes_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, util.Query, "", "app.gndr.graph.getMutes", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
