// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.graph.muteActorList

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// GraphMuteActorList_Input is the input argument to a app.gndr.graph.muteActorList call.
type GraphMuteActorList_Input struct {
	List string `json:"list" cborgen:"list"`
}

// GraphMuteActorList calls the XRPC method "app.gndr.graph.muteActorList".
func GraphMuteActorList(ctx context.Context, c util.LexClient, input *GraphMuteActorList_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "app.gndr.graph.muteActorList", nil, input, nil); err != nil {
		return err
	}

	return nil
}
