// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.labeler.getServices

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// LabelerGetServices_Output is the output of a app.gndr.labeler.getServices call.
type LabelerGetServices_Output struct {
	Views []*LabelerGetServices_Output_Views_Elem `json:"views" cborgen:"views"`
}

type LabelerGetServices_Output_Views_Elem struct {
	LabelerDefs_LabelerView         *LabelerDefs_LabelerView
	LabelerDefs_LabelerViewDetailed *LabelerDefs_LabelerViewDetailed
}

func (t *LabelerGetServices_Output_Views_Elem) MarshalJSON() ([]byte, error) {
	if t.LabelerDefs_LabelerView != nil {
		t.LabelerDefs_LabelerView.LexiconTypeID = "app.gndr.labeler.defs#labelerView"
		return json.Marshal(t.LabelerDefs_LabelerView)
	}
	if t.LabelerDefs_LabelerViewDetailed != nil {
		t.LabelerDefs_LabelerViewDetailed.LexiconTypeID = "app.gndr.labeler.defs#labelerViewDetailed"
		return json.Marshal(t.LabelerDefs_LabelerViewDetailed)
	}
	return nil, fmt.Errorf("cannot marshal empty enum")
}
func (t *LabelerGetServices_Output_Views_Elem) UnmarshalJSON(b []byte) error {
	typ, err := util.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "app.gndr.labeler.defs#labelerView":
		t.LabelerDefs_LabelerView = new(LabelerDefs_LabelerView)
		return json.Unmarshal(b, t.LabelerDefs_LabelerView)
	case "app.gndr.labeler.defs#labelerViewDetailed":
		t.LabelerDefs_LabelerViewDetailed = new(LabelerDefs_LabelerViewDetailed)
		return json.Unmarshal(b, t.LabelerDefs_LabelerViewDetailed)

	default:
		return nil
	}
}

// LabelerGetServices calls the XRPC method "app.gndr.labeler.getServices".
func LabelerGetServices(ctx context.Context, c util.LexClient, detailed bool, dids []string) (*LabelerGetServices_Output, error) {
	var out LabelerGetServices_Output

	params := map[string]interface{}{}
	if detailed {
		params["detailed"] = detailed
	}
	params["dids"] = dids
	if err := c.LexDo(ctx, util.Query, "", "app.gndr.labeler.getServices", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
