// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.notification.registerPush

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// NotificationRegisterPush_Input is the input argument to a app.gndr.notification.registerPush call.
type NotificationRegisterPush_Input struct {
	AppId      string `json:"appId" cborgen:"appId"`
	Platform   string `json:"platform" cborgen:"platform"`
	ServiceDid string `json:"serviceDid" cborgen:"serviceDid"`
	Token      string `json:"token" cborgen:"token"`
}

// NotificationRegisterPush calls the XRPC method "app.gndr.notification.registerPush".
func NotificationRegisterPush(ctx context.Context, c util.LexClient, input *NotificationRegisterPush_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "app.gndr.notification.registerPush", nil, input, nil); err != nil {
		return err
	}

	return nil
}
