// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.notification.updateSeen

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// NotificationUpdateSeen_Input is the input argument to a app.gndr.notification.updateSeen call.
type NotificationUpdateSeen_Input struct {
	SeenAt string `json:"seenAt" cborgen:"seenAt"`
}

// NotificationUpdateSeen calls the XRPC method "app.gndr.notification.updateSeen".
func NotificationUpdateSeen(ctx context.Context, c util.LexClient, input *NotificationUpdateSeen_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "app.gndr.notification.updateSeen", nil, input, nil); err != nil {
		return err
	}

	return nil
}
