// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.notification.getUnreadCount

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// NotificationGetUnreadCount_Output is the output of a app.gndr.notification.getUnreadCount call.
type NotificationGetUnreadCount_Output struct {
	Count int64 `json:"count" cborgen:"count"`
}

// NotificationGetUnreadCount calls the XRPC method "app.gndr.notification.getUnreadCount".
func NotificationGetUnreadCount(ctx context.Context, c util.LexClient, priority bool, seenAt string) (*NotificationGetUnreadCount_Output, error) {
	var out NotificationGetUnreadCount_Output

	params := map[string]interface{}{}
	if priority {
		params["priority"] = priority
	}
	if seenAt != "" {
		params["seenAt"] = seenAt
	}
	if err := c.LexDo(ctx, util.Query, "", "app.gndr.notification.getUnreadCount", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
