// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.unspecced.getSuggestedStarterPacks

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// UnspeccedGetSuggestedStarterPacks_Output is the output of a app.gndr.unspecced.getSuggestedStarterPacks call.
type UnspeccedGetSuggestedStarterPacks_Output struct {
	StarterPacks []*GraphDefs_StarterPackView `json:"starterPacks" cborgen:"starterPacks"`
}

// UnspeccedGetSuggestedStarterPacks calls the XRPC method "app.gndr.unspecced.getSuggestedStarterPacks".
func UnspeccedGetSuggestedStarterPacks(ctx context.Context, c util.LexClient, limit int64) (*UnspeccedGetSuggestedStarterPacks_Output, error) {
	var out UnspeccedGetSuggestedStarterPacks_Output

	params := map[string]interface{}{}
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, util.Query, "", "app.gndr.unspecced.getSuggestedStarterPacks", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
