// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.unspecced.applyLabels

import (
	"context"

	comatprototypes "github.com/gander-social/gander-indigo-sovereign/api/atproto"
	"github.com/gander-social/gander-indigo-sovereign/xrpc"
)

// UnspeccedApplyLabels_Input is the input argument to a app.gndr.unspecced.applyLabels call.
type UnspeccedApplyLabels_Input struct {
	Labels []*comatprototypes.LabelDefs_Label `json:"labels" cborgen:"labels"`
}

// UnspeccedApplyLabels calls the XRPC method "app.gndr.unspecced.applyLabels".
func UnspeccedApplyLabels(ctx context.Context, c *xrpc.Client, input *UnspeccedApplyLabels_Input) error {
	if err := c.Do(ctx, xrpc.Procedure, "application/json", "app.gndr.unspecced.applyLabels", nil, input, nil); err != nil {
		return err
	}

	return nil
}
