// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.unspecced.getSuggestedFeedsSkeleton

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// UnspeccedGetSuggestedFeedsSkeleton_Output is the output of a app.gndr.unspecced.getSuggestedFeedsSkeleton call.
type UnspeccedGetSuggestedFeedsSkeleton_Output struct {
	Feeds []string `json:"feeds" cborgen:"feeds"`
}

// UnspeccedGetSuggestedFeedsSkeleton calls the XRPC method "app.gndr.unspecced.getSuggestedFeedsSkeleton".
//
// viewer: DID of the account making the request (not included for public/unauthenticated queries).
func UnspeccedGetSuggestedFeedsSkeleton(ctx context.Context, c util.LexClient, limit int64, viewer string) (*UnspeccedGetSuggestedFeedsSkeleton_Output, error) {
	var out UnspeccedGetSuggestedFeedsSkeleton_Output

	params := map[string]interface{}{}
	if limit != 0 {
		params["limit"] = limit
	}
	if viewer != "" {
		params["viewer"] = viewer
	}
	if err := c.LexDo(ctx, util.Query, "", "app.gndr.unspecced.getSuggestedFeedsSkeleton", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
