// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.video.uploadVideo

import (
	"context"
	"io"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// VideoUploadVideo_Output is the output of a app.gndr.video.uploadVideo call.
type VideoUploadVideo_Output struct {
	JobStatus *VideoDefs_JobStatus `json:"jobStatus" cborgen:"jobStatus"`
}

// VideoUploadVideo calls the XRPC method "app.gndr.video.uploadVideo".
func VideoUploadVideo(ctx context.Context, c util.LexClient, input io.Reader) (*VideoUploadVideo_Output, error) {
	var out VideoUploadVideo_Output
	if err := c.LexDo(ctx, util.Procedure, "video/mp4", "app.gndr.video.uploadVideo", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
