// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package gndr

// schema: app.gndr.video.getJobStatus

import (
	"context"

	"github.com/gander-social/gander-indigo-sovereign/lex/util"
)

// VideoGetJobStatus_Output is the output of a app.gndr.video.getJobStatus call.
type VideoGetJobStatus_Output struct {
	JobStatus *VideoDefs_JobStatus `json:"jobStatus" cborgen:"jobStatus"`
}

// VideoGetJobStatus calls the XRPC method "app.gndr.video.getJobStatus".
func VideoGetJobStatus(ctx context.Context, c util.LexClient, jobId string) (*VideoGetJobStatus_Output, error) {
	var out VideoGetJobStatus_Output

	params := map[string]interface{}{}
	params["jobId"] = jobId
	if err := c.LexDo(ctx, util.Query, "", "app.gndr.video.getJobStatus", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
